name: Unit Test

on:
  push:
    branches: [master]

jobs:
  typescript-job:
    name: Typescript Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run: npm ci
      - name: Test with jest
        run: npm test

  python-job:
    name: Python Job
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
          architecture: "x64"
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Python Syntax Checker
        uses: cclauss/Find-Python-syntax-errors-action@v0.2.0
      - name: Test with pytest
        run: python -m pytest



